---
# file: roles/lttng/tasks/main.yml
- name: Install LTTng packages
  apt:
    name:
      - lttng-tools
      - lttng-modules-dkms
      - liblttng-ust-dev
      - babeltrace2
    state: present
    update_cache: yes
  notify: enable lttng # roles/lttng/handlers/main.yml
