---
# file: roles/mysql/handlers/main.yml
- name: enable mysql
  ansible.builtin.systemd:
    name: mysql
    state: started
    enabled: yes

- name: start mysql
  ansible.builtin.systemd:
    name: mysql
    state: started

- name: restart mysql
  ansible.builtin.systemd:
    name: mysql
    state: restarted

- name: stop mysql
  ansible.builtin.systemd:
    name: mysql
    state: stopped
