---
# file: roles/mysql/tasks/main.yml
- name: Install MySQL server
  apt:
    name: mysql-server
    state: present
  notify:
    - enable mysql
    - start mysql

- name: Copy MySQL configuration file
  ansible.builtin.template:
    src: templates/etc_mysql_mysql.conf.d_mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    owner: root
    group: root
    mode: '0700'
  notify:
    - restart mysql

- name: Uninstall MySQL server
  apt:
    name: mysql-server
    state: absent
  when: mysql_installation == false
  notify:
    - stop mysql
  tags:
    - never # never run this by default
    - cleanup
    - mysql
  when:
    - "'cleanup' in ansible_run_tags"
    - "'mysql' in ansible_run_tags"
