---
# file: roles/nginx/tasks/main.yml
- name: Install Nginx
  apt:
    name: nginx
    state: present
  notify:
    - enable Nginx
    - start Nginx

- name: Copy Nginx configuration file
  ansible.builtin.template:
    src: templates/etc_nginx_nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart Nginx

- name: Copy default site configuration file
  ansible.builtin.template:
    src: templates/etc_nginx_conf.d_default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify:
    - restart Nginx

- name: Uninstall Nginx
  apt:
    name: nginx
    state: absent
  when: nginx_installation == false
  notify:
    - stop Nginx
    - disable Nginx
  tags: cleanup
