---
# file: roles/nginx/handlers/main.yml
- name: start Nginx
  ansible.builtin.systemd:
    name: nginx
    state: started

- name: restart Nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: enable Nginx
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
